// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsbnptuqoreumobxgyxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzYm5wdHVxb3JldW1vYnhneXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzU4MDcsImV4cCI6MjA2ODk1MTgwN30.4oiITrzivJ96-msgDG3hMN2-Y9sJa9CzAMULhXjXxNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});